adding consolidation.py

diff --git a/.github/workflows/CD.yaml b/.github/workflows/CD.yaml
--- a/.github/workflows/CD.yaml
+++ b/.github/workflows/CD.yaml
@@ -12,23 +12,23 @@ jobs:
       fail-fast: false
       matrix:
         include:
-          - OS_CPU: win-64
+          - OS: win-64
             VM: windows-latest            
-          - OS_CPU: linux-64
-            VM: linux-latest
-          # - OS_CPU: linux-aarch64
-          #   VM: linux-latest
-          #   DOCKER_image: xyz
-          - OS_CPU: osx-64
+          - OS: linux-64
+            VM: ubuntu-latest
+          - OS: osx-64
             VM: macos-latest
-          # - OS_CPU: osx-arm64
-          #   VM: macos-latest
-          #   DOCKER_IMG: xyz      
+          - OS: linux-aarch64
+            VM: ubuntu-latest
+            DOCKER_IMG: condaforge/linux-anvil-aarch64
+          - OS: osx-arm64
+            VM: macos-latest
+            DOCKER_IMG: xyz      
     steps:  
     - name: Checkout code
       uses: actions/checkout@v2
 
-    - name: Setup conda environment
+    - name: Set up conda environment
       uses: conda-incubator/setup-miniconda@v2
       with:
         miniconda-version: latest
@@ -36,22 +36,59 @@ jobs:
         environment-file: requirements.yml
         channel-priority: strict
 
-    - name: build and upload
+    - name: Build and upload
+      shell: bash -l {0}
+      env:
+        OS: ${{ matrix.OS }}
+        DOCKER_IMG: ${{ matrix.DOCKER_IMG }}
+        CONDA_UPLOAD_TOKEN: ${{ secrets.CONDA_UPLOAD_TOKEN }}
+        MAXICONDA_ENV_RELEASE: ${GITHUB_REF##*/}
+      run: |
+        if [[ "$OS" == "linux-aarch64" ]]; then
+          echo "Solving Environments for linux-aarch64"
+        elif [[ "$OS" == "osx-arm64" ]]; then
+          echo "Solving Environments for osx-arm64"
+        else
+          echo ">>>>> Build and upload environments for $OS <<<<<"
+          python -u scripts/build.py
+        fi
+
+  consolidate:
+    runs-on: ubuntu-latest
+    steps:
+    - name: Checkout code
+      uses: actions/checkout@v2
+      with:
+        persist-credentials: false  # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
+        fetch-depth: 0  # otherwise, you will failed to push refs to dest repo
+
+    - name: Set up conda environment
+      uses: conda-incubator/setup-miniconda@v2
+      with:
+        miniconda-version: latest
+        activate-environment: maxiconda-envs
+        environment-file: environment.yaml
+        channel-priority: strict
+
+    - name: consolidate
       shell: bash -l {0}
       env:
         CONDA_UPLOAD_TOKEN: ${{ secrets.CONDA_UPLOAD_TOKEN }}
         MAXICONDA_ENV_RELEASE: ${GITHUB_REF##*/}
       run: |
-        python -u scripts/build.py --and-upload
-
-  # consolidate:
-  #   runs-on: linux-latest
-  #   steps:
-  #   - name: consolidate
-  #     shell: bash -l {0}
-  #     env:
-  #       CONDA_UPLOAD_TOKEN: ${{ secrets.CONDA_UPLOAD_TOKEN }}
-  #       MAXICONDA_ENV_RELEASE: ${GITHUB_REF##*/}
-  #     run: |
-  #       python -u scripts/build.py --and-upload
+        python -u scripts/consolidate.py
   
+    - name: Commit files
+      run: |
+        git config --local user.email "action@github.com"
+        git config --local user.name "GitHub Action"
+        git add . || echo "ignore adding files, proceed"
+        git commit -m "Update packages ${{ matrix.OS_CPU }}" || echo "ignore commit failure, proceed"
+
+    - name: Push changes
+      uses: ad-m/github-push-action@v0.6.0
+      with:
+        github_token: ${{ secrets.TOKEN_GITHUB }}
+        branch: main
+        directory: "../maxiconda-envs"
+        repository: Semi-ATE/maxiconda-envs
